replicaCount: 1

fullnameOverride: "storage"

image: "storage:0.2.14"

service:
  type: ClusterIP
  port: 9000

postgresql:
  enabled: true
  postgresqlUsername: storageuser
  postgresqlPassword: storagepasswd
  postgresqlDatabase: storagedb
  persistence:
    size: 0.1Gi
  service:
    port: "5432"