apiVersion: skaffold/v2beta2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: notification
    context: .
deploy:
  helm:
    releases:
    - name: notification
      chartPath: notification-chart
      skipBuildDependencies: true
      values:
        image: notification
