replicaCount: 1

fullnameOverride: "auth"

image: "auth:0.1.0"

service:
  type: ClusterIP
  port: 9000

postgresql:
  name: pg_dev
  enabled: true
  postgresqlUsername: appuser
  postgresqlPassword: apppasswd
  postgresqlDatabase: appdb
  persistence:
    size: 0.1Gi
  service:
    port: "5432"

ingress:
  enabled: false
  hosts:
    - host: arch.homework
      paths: ["/auth"]
