apiVersion: skaffold/v2beta2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: storage
    context: .
deploy:
  helm:
    releases:
    - name: storage
      chartPath: storage-chart
      skipBuildDependencies: true
      values:
        image: storage
