replicaCount: 1

fullnameOverride: "order"

image: "order:0.2.14"

service:
  type: ClusterIP
  port: 9000

postgresql:
  enabled: true
  postgresqlUsername: orderuser
  postgresqlPassword: orderpasswd
  postgresqlDatabase: orderdb
  persistence:
    size: 0.1Gi
  service:
    port: "5432"