apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
  pgusername: cG9zdGdyZXM= #postgres
  pgpassword: cGdwYXNz #pgpass
  username: dXNlcmFwcA== #userapp
  password: dXNlcmFwcHBhc3M= #userapppass  