{
 "title": "otus-dz5",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Latency 99",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(uri, le) (rate(http_server_requests_seconds_bucket{uri=~\"/user.*\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 95",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(uri, le) (rate(http_server_requests_seconds_bucket{uri=~\"/user.*\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 50",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(uri, le) (rate(http_server_requests_seconds_bucket{uri=~\"/user.*\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Max",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(uri, le) (rate(http_server_requests_seconds_bucket{uri=~\"/user.*\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_bucket{uri=~\"/user.*\", status=~\"50.+\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"/user.*\"}[2m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx-Ingress 5xx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_request_duration_seconds_bucket{status=~\"50.+\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx-Ingress RPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[2m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}