apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  DATASOURCE_URL: "jdbc:postgresql://dev-pg-postgresql:5432/userapp?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;connectionCollation=utf8_general_ci&amp;characterSetResults=UTF-8"
